### ISSUE TITLE
User Story #2

### ISSUE THREAD

**Issue by GrantKop** [JackoBright/TeamApollo-SpaceShipSimulator1000#10]
As an astronaut, I want to be able to train my spaceship flying skills, so that when I go into space I can confidently and safely operate my vehicle.

Background:
-Makes spaceship training cheaper and more accessible
-Creates a safe and accurate environment for practicing
-Astronauts
-Space ship driving enthusiasts 

Requirements:
-Accurate physics close to real life
-Easy to understand U.I. and controls

Dependencies
-Must be built on an accurate physics engine

Subtasks
-Create / collect assets for the U.I. and objects
-Research physics and learn how to create an accurate physics engine

Estimate: A core gameplay mechanic, hopefully perfected by the end of the project

Acceptance Criteria:
At least 90% accuracy with the physics engine

DoD:
-Task passed the acceptance criteria
-Has been pushed to production

**Comment by JackoBright** [comment]
Old version, created new one using projects
